# Generated by Django 4.0.3 on 2022-03-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_useraddressbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressbook',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
