# Generated by Django 4.0.2 on 2022-03-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_banner_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
